### ISSUE TITLE
QuickDebug.h not found

### ISSUE THREAD

**Issue by CodeMonkO** [gmag11/QuickESPNow#2]
Steps to reproduce

1. Added library to arduino
2. Tried compiling, but failed with error "QuickDebug.h" could be located.

I checked you code. it looks like you have used DEBUG_DBG to print debug logs. 

Solution

1. Please add "QuickDebug.h"

**Comment by alastaira** [comment]
Can confirm I just encountered exactly the same issue.

**Comment by cyrilpreiss** [comment]
same issue here

**Comment by gmag11** [comment]
You need to install https://github.com/gmag11/QuickDebug too

**Comment by gmag11** [comment]
With latest release (https://github.com/gmag11/QuickESPNow/releases/tag/0.7.0) QuickDebug is not required if you don't need to get debug messages
