### ISSUE TITLE
Comparison to Simple ESP Now

### ISSUE THREAD

**Issue by alastaira** [gmag11/QuickESPNow#3]
Just wondered if you were aware of the existing Simple ESP Now project, which seems to be intended to achieve much the same aims as Quick ESP Now?
https://github.com/saghonfly/SimpleEspNowConnection

As a new user looking to simplify the boilerplate code to use ESP Now, it would be great to add a simple comparison to the description to enable an informed choice which one has the more suitable features/performance :)

**Comment by gmag11** [comment]
Hi, I did not know about it. Thank you.

I've had a look to that project and I guess its intention is similar to this one: Simplify the use of esp-now.

[SimpleEspNowConnection](https://github.com/saghonfly/SimpleEspNowConnection) implements some mechanisms to associate a node (client) with a gateway (server). Besides it is able to split long messages to overcome the 250 bytes limitation.

My library tries to solve this at a lower level. Just send and receive plain data peer to peer without association, data splitting neither node - client differentiation.

So, using this should be easier but those things have to be solved at a higher level if needed.

One extra of my library is that it gives RSSI (received power) for every packet, that is useful information to guess rough distance from sender to receiver.

Both libraries try to cover different use cases so I think there is space for them two :) Test both examples and decide by yourself which one fits better into your development.
