### ISSUE TITLE
Using struct

### ISSUE THREAD

**Issue by svdrummer** [gmag11/QuickESPNow#4]
Hello and thanks for sharing
Is it possible to add a STRUCT type message for the data sent. Just to make it easier to send items in the message and break them out later?

**Comment by gmag11** [comment]
Hi, you can send whatever you want with the only condition to not exceed 250 bytes length. Just cast your struct as `uint8_t*` and do the opposite in the other side.

For this task sometimes I it is more convenient to use ArduinoJSON library to build a JSON string. This library includes support for MsgPack format that compacts json data to use less bytes.
