### ISSUE TITLE
QuickDebug.h: No such file or directory

### ISSUE THREAD

**Issue by homoaroma** [gmag11/QuickESPNow#5]
Arduino\libraries\QuickESPNow-main\src/QuickEspNow_esp32.h:15:24: fatal error: QuickDebug.h: No such file or directory
compilation terminated.

**Comment by homoaroma** [comment]
Sorry, I found out that I need to install another library.

**Comment by blazoncek** [comment]
I would like this to be optional as I already use other debugging environment.

**Comment by yanxke** [comment]
Should add a dependency so the library is automatically installed.

**Comment by gmag11** [comment]
Hi, actually it is added as a dependency but it does not get installed for some people.
I use it for development without having to use print but I thought I could be useful for others.

But many people get confused with that message and maybe it is better to remove it.

What do you think?

**Comment by blazoncek** [comment]
It is useful (I intend to integrate it into our project but will be major task) it is just unnecessarily included here when used as a library in other projects.

**Comment by yanxke** [comment]
I tried to install it manually but it still doesn't compile. I think that library has other dependencies and so I ended up making dummy definitions for the macros and a skeleton .h file. It's the only way I could get this library to compile. I'm using PlatformIO FWIW.

**Comment by gmag11** [comment]
With latest release (https://github.com/gmag11/QuickESPNow/releases/tag/0.7.0) QuickDebug is not required if you don't need to get debug messages
